---
GProject: 123
GToken: string
GURL: string
GUser: string
MBad: x
MDone: trophy
MDown: thumbsdown
MFail: poop
MGood: heavy_check_mark
MUp: thumbsup
VBackend:
  - user1
  - user2
VFrontend:
  - user1
  - user2
